server:
  error:
    include-message: always
    include-binding-errors: always
  port: ${PORT:8080}

DB_DRIVER_CLASS: ${DB_DRIVER_CLASS}
DB_BASE_URL: ${DB_BASE_URL}
DB_USER: ${DB_USER}
DB_PASSWORD: ${DB_PASSWORD}
DB_DDL_AUTO: ${DB_DDL_AUTO}
DB_DIALECT: ${DB_DIALECT}

spring:    
  application:
    name: users
  datasource:
    url: ${DB_BASE_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: ${DB_DRIVER_CLASS}
  jpa:
    hibernate:
      ddl-auto: ${DB_DDL_AUTO}
    properties:
      hibernate:
        dialect: ${DB_DIALECT}
        format_sql: true
    show-sql: false

  
resend:
  api:
    key: ${RESEND_API_KEY}

jwt:
  secret: ${JWT_SECRET}
  expiration: ${JWT_EXPIRATION}
logging:
  level:
    '[org.springframework.web]': DEBUG
    '[org.springframework.security]': DEBUG
    '[HobbyList.example.HobbyList]': DEBUG